ALTER SESSION SET "_oracle_script" = TRUE;
ALTER SESSION SET CONTAINER = cdb$root;
ALTER SESSION SET CONTAINER = pdb_pot;

--1
CREATE TABLESPACE TS_PAV
  DATAFILE 'C:\app\Tablespaces\TS_PAV.dbf'
  SIZE 7M
  AUTOEXTEND ON NEXT 5M
  MAXSIZE 30M
  EXTENT MANAGEMENT LOCAL;
  
--2
CREATE TEMPORARY TABLESPACE TS_TEMP_PAV
  TEMPFILE 'C:\app\Tablespaces\TS_TEMP_PAV.dbf'
  SIZE 5M
  AUTOEXTEND ON NEXT 3M
  MAXSIZE 20M
  EXTENT MANAGEMENT LOCAL;
  
--3
SELECT TABLESPACE_NAME, STATUS, contents logging from SYS.DBA_TABLESPACES;

--5
CREATE ROLE RL_PAVCORE;

--4
SELECT FILE_NAME, TABLESPACE_NAME, STATUS, MAXBYTES, USER_BYTES FROM DBA_DATA_FILES
UNION
SELECT FILE_NAME, TABLESPACE_NAME, STATUS, MAXBYTES, USER_BYTES FROM DBA_DATA_FILES;

GRANT CREATE SESSION,
      CREATE TABLE,
      CREATE VIEW,
      CREATE PROCEDURE TO RL_PAVCORE;
      
--6, 7
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'RL_PAVCORE';
SELECT * FROM DBA_SYS_PRIVS;

--8
CREATE PROFILE PF_PAVCORE LIMIT
  PASSWORD_LIFE_TIME 180
  SESSIONS_PER_USER 3
  FAILED_LOGIN_ATTEMPTS 7
  PASSWORD_LOCK_TIME 1
  PASSWORD_REUSE_TIME 10
  PASSWORD_GRACE_TIME DEFAULT
  CONNECT_TIME 180
  IDLE_TIME 30;

--9, 10, 11
SELECT * FROM DBA_PROFILES;
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'PF_PAVCORE';
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'DEFAULT';

--12
CREATE USER PAVCORE IDENTIFIED BY 123
DEFAULT TABLESPACE TS_PAV 
TEMPORARY TABLESPACE TS_TEMP_PAV 
PROFILE PF_PAVCORE
ACCOUNT UNLOCK
PASSWORD EXPIRE

GRANT RL_PAVCORE TO PAVCORE

--16
ALTER USER PAVCORE
DEFAULT TABLESPACE TS_PAV
QUOTA 2M ON TS_PAV;

SELECT NAME. PDB FROM V$SERVICES;
SELECT name, OPEN_MODE FROM v$PDBS;

DROP TABLESPACE TS_TEMP_PAV INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE TS_PAV INCLUDING CONTENTS AND DATAFILES;
DROP ROLE RL_PAVCORE;
DROP PROFILE PF_PAVCORE CASCADE;
DROP USER PAVCORE CASCADE;
DROP TABLE PAV_T;

--15
CREATE TABLE PAV_T(
    id NUMBER PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL
);

--17
INSERT INTO PAV_T VALUES (1, 'Molly', 'Kane');
INSERT INTO PAV_T VALUES (2, 'Molly', 'Kane');
INSERT INTO PAV_T VALUES (3, 'Molly', 'Kane');
INSERT INTO PAV_T VALUES (4, 'Molly', 'Kane');
INSERT INTO PAV_T VALUES (5, 'Molly', 'Kane');
INSERT INTO PAV_T VALUES (6, 'Molly', 'Kane');
INSERT INTO PAV_T VALUES (7, 'Molly', 'Kane');
INSERT INTO PAV_T VALUES (8, 'Molly', 'Kane');
INSERT INTO PAV_T VALUES (9, 'Molly', 'Kane');
INSERT INTO PAV_T VALUES (10, 'Molly', 'Kane');

--19
SELECT * FROM PAV_T;

--18
ALTER TABLESPACE TS_PAV OFFLINE;
--20
ALTER TABLESPACE TS_PAV ONLINE;

