--1 
SELECT SUM(VALUE) FROM V$SGA;
--2
SELECT * FROM V$SGA;
SELECT POOL, NAME, BYTES FROM V$SGASTAT;
--3
SELECT * FROM V$SGAINFO WHERE name = 'Granule Size';

SELECT 
    COMPONENT,
    MAX_SIZE, 
    LAST_OPER_MODE,
    LAST_OPER_TIME,
    GRANULE_SIZE,
    CURRENT_SIZE/GRANULE_SIZE AS RATIO
FROM V$SGA_DYNAMIC_COMPONENTS
WHERE CURRENT_SIZE > 0;
--4
SELECT * FROM V$SGASTAT WHERE NAME = 'free memory';
--5
SELECT COMPONENT, MIN_SIZE, CURRENT_SIZE FROM V$SGA_DYNAMIC_COMPONENTS;
--7
CREATE TABLE KEEPTABLE 
(
ID NUMBER
) 
STORAGE(BUFFER_POOL KEEP) TABLESPACE USERS;

INSERT INTO KEEPTABLE VALUES(1);
SELECT DISTINCT * FROM DBA_SEGMENTS WHERE SEGMENT_NAME = 'KEEPTABLE';
--8
CREATE TABLE DEFAULTTABLE 
(
ID NUMBER
) 
STORAGE(BUFFER_POOL DEFAULT) TABLESPACE USERS;

INSERT INTO DEFAULTTABLE VALUES(1);
SELECT DISTINCT * FROM DBA_SEGMENTS WHERE SEGMENT_NAME = 'DEFAULTTABLE';
--9
SHOW PARAMETER LOG_BUFFER;
--10
SELECT * FROM V$SGASTAT WHERE NAME = 'free memory' AND pool = 'large pool';
--11
SELECT USERNAME, SERVICE_NAME, SERVER FROM V$SESSION WHERE USERNAME IS NOT NULL;
--12
SELECT * FROM V$SESSION WHERE TYPE ='BACKGROUND';
--13
SELECT    s.username,s.module,s.osuser,p.program,s.logon_time,s.terminal, p.spid
FROM v$session s, v$process p
WHERE s.paddr = p.addr;
--14
SELECT COUNT(*) FROM V$BGPROCESS WHERE NAME LIKE 'DBWn%';
SELECT * FROM V$BGPROCESS WHERE NAME LIKE 'DBWn%';
--15
ALTER SESSION SET CONTAINER = cdb$root;
ALTER SESSION SET CONTAINER = PDB_POT;
SELECT NAME, NETWORK_NAME, PDB FROM V$SERVICES;
SELECT USERNAME, SERVICE_NAME, SERVER FROM V$SESSION WHERE USERNAME IS NOT NULL;
--16
SHOW PARAMETER DISPATCHER;
--17, 18 C:\app\potbstu\product\12.1.0\dbhome_1\NETWORK\ADMIN
--19
